replicaCount: 1

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

service:
  type: ClusterIP
  port: 9000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: console.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}
